export const All_PRODUCTS_REQUEST = 'All_PRODUCTS_REQUEST'
export const  All_PRODUCTS_SUCCESS = 'All_PRODUCTS_SUCCESS'
export const All_PRODUCTS_FAIL = 'All_PRODUCTS_FAIL'


export const PRODUCT_DETAILS_REQUEST = 'All_PRODUCTS_REQUEST'
export const PRODUCT_DETAILS_SUCCESS = 'All_PRODUCTS_SUCCESS'
export const PRODUCT_DETAILS_FAIL = 'All_PRODUCTS_FAIL'


export const CLEAR_ERRORS  = 'All_PRODUCTS_REQUEST'